apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
spec:
  generators:
  - git:
      repoURL: https://github.com/m3t41/gitops-managed-apps.git
      revision: HEAD
      files:
      - path: openshift/**/config.json
  template:
    metadata:
      name: '{{namespace}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/m3t41/gitops-managed-apps.git
        targetRevision: HEAD
        path: '{{path.filename}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}'