apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
spec:
  generators:
  - git:
      repoURL: https://github.com/m3t41/gitops-managed-apps.git
      revision: HEAD
      directories:
      - path: k8s/**/config.json
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/m3t41/gitops-managed-apps.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: {{server}}
        namespace: {{path.1}}
