apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
spec:
  generators:
  - git:
      repoURL: https://github.com/m3t41/gitops-managed-apps.git
      revision: HEAD
      files:
      - path: openshift/**/config.json
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: '{{repo}}'
        targetRevision: HEAD
        path: '{{folder}}'
      destination:
        server: https://kubernetes.default.svc
        #server: https://49.12.216.11:6443
        namespace: '{{namespace}}'
