apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationsetopenshift
spec:
  generators:
  - git:
      repoURL: https://github.com/m3t41/gitops-managed-apps.git
      revision: HEAD
      files:
      - path: openshift/**/config.json
  template:
    metadata:
      name: '{{appsetname}}'
    spec:
      project: default
      source:
        repoURL: '{{repourl}}'
        targetRevision: HEAD
        path: '{{repofolder}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
